-- STL Unclaimed System Database Schema
-- Last Updated: 2025-12-25
-- 
-- Recent Changes:
-- - Added bet_amount column to Unclaimed and OverAllCollections tables (2025-12-25)
-- - Added area column to OverAllCollections table (2025-12-25)
-- - Added receipt_image column to Unclaimed and OverAllCollections tables
-- - Added mode column (Cash, Back Transfer, Deposited, Gcash, Cebuana, Palawan)
-- - Added payment_type column (Full Payment, Partial Payment)
-- - Added charge_amount column to Unclaimed table
-- - Updated trigger to copy receipt_image, mode, payment_type, bet_amount, and area to collections
-- - Fixed charge_amount calculation in trigger (now uses actual charge_amount field)

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users Table
-- Stores system users and their authentication details
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, -- Note: In production, use Supabase Auth and hashed passwords
    fullname TEXT NOT NULL,
    contact_number TEXT,
    role TEXT NOT NULL DEFAULT 'staff', -- admin, checker, general manager, specialist, collector, staff
    franchising_name TEXT,
    status TEXT NOT NULL DEFAULT 'active', -- active, inactive, suspended
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Unclaimed Table
-- Stores all winning items that haven't been claimed initially
CREATE TABLE IF NOT EXISTS "Unclaimed" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teller_name TEXT NOT NULL,
    bet_number TEXT NOT NULL,
    draw_date DATE NOT NULL,
    bet_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- Original bet amount
    win_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    net NUMERIC(15, 2) NOT NULL DEFAULT 0,
    charge_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    franchise_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Unclaimed', -- Unclaimed, Collected, Cancelled
    return_date TIMESTAMPTZ,
    area TEXT,
    collector TEXT,
    mode TEXT DEFAULT 'Cash', -- Cash, Back Transfer, Deposited, Gcash, Cebuana, Palawan
    payment_type TEXT DEFAULT 'Full Payment', -- Full Payment, Partial Payment
    receipt_image TEXT, -- URL to transaction receipt image in Supabase Storage
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. OverAllCollections Table
-- Stores items that have been moved to collected status
CREATE TABLE IF NOT EXISTS "OverAllCollections" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unclaimed_id BIGINT REFERENCES "Unclaimed"(id) ON DELETE CASCADE,
    teller_name TEXT NOT NULL,
    bet_number TEXT NOT NULL,
    draw_date DATE NOT NULL,
    return_date TIMESTAMPTZ NOT NULL,
    bet_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- Original bet amount
    amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    charge_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    net NUMERIC(15, 2) NOT NULL DEFAULT 0,
    collector TEXT,
    franchise_name TEXT NOT NULL,
    area TEXT, -- Area field
    mode TEXT, -- Cash, Back Transfer, Deposited, Gcash, Cebuana, Palawan
    payment_type TEXT, -- Full Payment, Partial Payment
    receipt_image TEXT, -- URL to transaction receipt image copied from Unclaimed
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Reports Table
-- Stores distribution breakdown for winnings
CREATE TABLE IF NOT EXISTS "Reports" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unclaimed_id BIGINT REFERENCES "Unclaimed"(id) ON DELETE CASCADE,
    teller_name TEXT,
    amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    collector TEXT,
    area TEXT,
    staff_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 10%
    collector_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 10%
    agent_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 30%
    admin_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 50%
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Pending View
-- A dynamic view for items overdue by more than 3 days
DROP VIEW IF EXISTS "Pending";

CREATE VIEW "Pending" AS
SELECT 
    id,
    teller_name,
    bet_number,
    draw_date,
    return_date,
    win_amount,
    franchise_name,
    collector,
    area,
    EXTRACT(DAY FROM (NOW() - draw_date::timestamp))::integer AS days_overdue
FROM "Unclaimed"
WHERE status = 'Unclaimed'
AND (NOW() - draw_date::timestamp) > INTERVAL '3 days';

-- 6. Automation Triggers
-- Automatically create collection and report when status changes to 'Collected'
CREATE OR REPLACE FUNCTION handle_unclaimed_collection()
RETURNS TRIGGER AS $$
BEGIN
    IF (OLD.status IS DISTINCT FROM 'Collected' AND NEW.status = 'Collected') THEN
        -- Insert into OverAllCollections
        INSERT INTO "OverAllCollections" (
            unclaimed_id, teller_name, bet_number, draw_date, 
            return_date, bet_amount, amount, charge_amount, net, 
            collector, franchise_name, area, receipt_image, mode, payment_type
        ) VALUES (
            NEW.id, NEW.teller_name, NEW.bet_number, NEW.draw_date,
            COALESCE(NEW.return_date, NOW()), COALESCE(NEW.bet_amount, 0), NEW.win_amount, 
            COALESCE(NEW.charge_amount, 0), NEW.net,
            COALESCE(NEW.collector, 'System'),
            NEW.franchise_name,
            NEW.area,
            NEW.receipt_image,
            COALESCE(NEW.mode, 'Cash'),
            COALESCE(NEW.payment_type, 'Full Payment')
        );

        -- Insert into Reports
        INSERT INTO "Reports" (
            unclaimed_id, teller_name, amount, collector, area,
            staff_amount, collector_amount, agent_amount, admin_amount
        ) VALUES (
            NEW.id, NEW.teller_name, NEW.win_amount, COALESCE(NEW.collector, 'System'), NEW.area,
            NEW.win_amount * 0.10, -- 10% Staff
            NEW.win_amount * 0.10, -- 10% Collector
            NEW.win_amount * 0.30, -- 30% Agent
            NEW.win_amount * 0.50  -- 50% Admin
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_unclaimed_collected
    AFTER UPDATE ON "Unclaimed"
    FOR EACH ROW
    WHEN (OLD.status IS DISTINCT FROM NEW.status)
    EXECUTE FUNCTION handle_unclaimed_collection();

-- 7. Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_unclaimed_updated_at BEFORE UPDATE ON "Unclaimed" FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 8. Seed Data
-- Default Users
INSERT INTO users (username, password, fullname, role, status) VALUES
('admin', 'admin123', 'Administrator', 'admin', 'active'),
('user', 'user1', 'checker1', 'checker', 'active'),
('GM', 'sgc123', 'GM1', 'general manager', 'active'),
('Rinalou', 'sgc123', 'Unclaimed Specialist', 'specialist', 'active')
ON CONFLICT (username) DO NOTHING;

-- Sample Unclaimed Items
INSERT INTO "Unclaimed" (teller_name, bet_number, draw_date, win_amount, net, franchise_name, status, area) VALUES
('Teller 1', '12-34', CURRENT_DATE - INTERVAL '1 day', 1000.00, 980.00, '5A Royal Gaming OPC', 'Unclaimed', 'Area 1'),
('Teller 2', '56-78', CURRENT_DATE - INTERVAL '5 days', 5000.00, 4900.00, 'Imperial Gnaing OPC', 'Unclaimed', 'Area 2'),
('Teller 1', '90-12', CURRENT_DATE - INTERVAL '10 days', 2500.00, 2450.00, 'Glowing Fortune OPC', 'Unclaimed', 'Area 1'),
('Teller 3', '34-56', CURRENT_DATE - INTERVAL '40 days', 10000.00, 9800.00, '5A Royal Gaming OPC', 'Unclaimed', 'Area 3');

-- Sample Collections
INSERT INTO "OverAllCollections" (teller_name, bet_number, draw_date, return_date, amount, charge_amount, net, collector, franchise_name) VALUES
('Teller 4', '11-22', CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '2 days', 2000.00, 40.00, 1960.00, 'Collector A', '5A Royal Gaming OPC');

-- Sample Reports
INSERT INTO "Reports" (teller_name, amount, collector, area, staff_amount, collector_amount, agent_amount, admin_amount) VALUES
('Teller 4', 2000.00, 'Collector A', 'Area 1', 200.00, 200.00, 600.00, 1000.00);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Unclaimed" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OverAllCollections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reports" ENABLE ROW LEVEL SECURITY;

-- Create basic RLS policies (Allowing authenticated access for all operations)
-- In production, these should be more restrictive based on roles
CREATE POLICY "Allow all to authenticated users" ON users FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated users" ON "Unclaimed" FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated users" ON "OverAllCollections" FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated users" ON "Reports" FOR ALL TO authenticated USING (true);

-- Also allow anon for now if public access is needed for testing
CREATE POLICY "Allow all to anon users" ON users FOR ALL TO anon USING (true);
CREATE POLICY "Allow all to anon users" ON "Unclaimed" FOR ALL TO anon USING (true);
CREATE POLICY "Allow all to anon users" ON "OverAllCollections" FOR ALL TO anon USING (true);
CREATE POLICY "Allow all to anon users" ON "Reports" FOR ALL TO anon USING (true);
