-- STL Unclaimed System Database Schema
-- Complete Schema with All Migrations Consolidated
-- Last Updated: 2025-12-27
-- 
-- This file includes:
-- - Base schema
-- - Cash deposit tracking
-- - Auto-calculate net amounts
-- - Uncollected status handling
-- - Sync updates to collections
-- - Security fixes
-- - Bet number in reports

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLES
-- ============================================================================

-- 1. Users Table
-- Stores system users and their authentication details
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    fullname TEXT NOT NULL,
    contact_number TEXT,
    role TEXT NOT NULL DEFAULT 'staff', -- admin, cashier, checker, general manager, specialist, collector, staff
    franchising_name TEXT,
    status TEXT NOT NULL DEFAULT 'active', -- active, inactive, suspended
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Unclaimed Table
-- Stores all winning items that haven't been claimed initially
CREATE TABLE IF NOT EXISTS "Unclaimed" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teller_name TEXT NOT NULL,
    bet_number TEXT NOT NULL,
    draw_date DATE NOT NULL,
    bet_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    win_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    net NUMERIC(15, 2) NOT NULL DEFAULT 0,
    charge_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    franchise_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Unclaimed', -- Unclaimed, Uncollected, Collected, Cancelled
    return_date TIMESTAMPTZ,
    area TEXT,
    collector TEXT,
    mode TEXT DEFAULT 'Cash', -- Cash, Back Transfer, Deposited, Gcash, Cebuana, Palawan
    payment_type TEXT DEFAULT 'Full Payment', -- Full Payment, Partial Payment
    receipt_image TEXT,
    reference_number TEXT, -- Transaction reference for non-cash payments
    -- Cash deposit tracking fields
    cash_deposited BOOLEAN DEFAULT FALSE,
    deposit_date TIMESTAMPTZ,
    deposit_amount DECIMAL(10, 2),
    deposit_receipt TEXT,
    cashier_name TEXT,
    bank_name TEXT,
    deposit_reference TEXT,
    -- Verification tracking
    verified_by TEXT,
    verified_at TIMESTAMPTZ,
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add comments for cash deposit fields
COMMENT ON COLUMN "Unclaimed".cash_deposited IS 'Whether cash has been deposited to the bank';
COMMENT ON COLUMN "Unclaimed".deposit_date IS 'Date and time when cash was deposited';
COMMENT ON COLUMN "Unclaimed".deposit_amount IS 'Amount deposited to the bank';
COMMENT ON COLUMN "Unclaimed".deposit_receipt IS 'URL to the deposit receipt image';
COMMENT ON COLUMN "Unclaimed".cashier_name IS 'Name of the cashier who deposited the cash';
COMMENT ON COLUMN "Unclaimed".bank_name IS 'Name of the bank where cash was deposited';
COMMENT ON COLUMN "Unclaimed".deposit_reference IS 'Bank deposit reference number';

-- 3. OverAllCollections Table
-- Stores items that have been moved to collected status
CREATE TABLE IF NOT EXISTS "OverAllCollections" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unclaimed_id BIGINT REFERENCES "Unclaimed"(id) ON DELETE CASCADE,
    teller_name TEXT NOT NULL,
    bet_number TEXT NOT NULL,
    draw_date DATE NOT NULL,
    return_date TIMESTAMPTZ NOT NULL,
    bet_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    charge_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    net NUMERIC(15, 2) NOT NULL DEFAULT 0,
    collector TEXT,
    franchise_name TEXT NOT NULL,
    area TEXT,
    mode TEXT,
    payment_type TEXT,
    receipt_image TEXT,
    -- Cash deposit tracking fields
    cash_deposited BOOLEAN DEFAULT FALSE,
    deposit_date TIMESTAMPTZ,
    deposit_amount DECIMAL(10, 2),
    deposit_receipt TEXT,
    cashier_name TEXT,
    bank_name TEXT,
    deposit_reference TEXT,
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add comments for cash deposit fields
COMMENT ON COLUMN "OverAllCollections".cash_deposited IS 'Whether cash has been deposited to the bank';
COMMENT ON COLUMN "OverAllCollections".deposit_date IS 'Date and time when cash was deposited';
COMMENT ON COLUMN "OverAllCollections".deposit_amount IS 'Amount deposited to the bank';
COMMENT ON COLUMN "OverAllCollections".deposit_receipt IS 'URL to the deposit receipt image';
COMMENT ON COLUMN "OverAllCollections".cashier_name IS 'Name of the cashier who deposited the cash';
COMMENT ON COLUMN "OverAllCollections".bank_name IS 'Name of the bank where cash was deposited';
COMMENT ON COLUMN "OverAllCollections".deposit_reference IS 'Bank deposit reference number';

-- 4. Reports Table
-- Stores distribution breakdown for winnings
CREATE TABLE IF NOT EXISTS "Reports" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unclaimed_id BIGINT REFERENCES "Unclaimed"(id) ON DELETE CASCADE,
    teller_name TEXT,
    bet_number TEXT,
    draw_date DATE,
    return_date TIMESTAMPTZ,
    franchise_name TEXT,
    amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    collector TEXT,
    area TEXT,
    staff_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 10%
    collector_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 10%
    agent_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 30%
    admin_amount NUMERIC(15, 2) NOT NULL DEFAULT 0, -- 50%
    total_charges NUMERIC(15, 2) NOT NULL DEFAULT 0, -- Charges deducted
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_unclaimed_cash_deposited ON "Unclaimed"(cash_deposited);
CREATE INDEX IF NOT EXISTS idx_unclaimed_deposit_date ON "Unclaimed"(deposit_date);
CREATE INDEX IF NOT EXISTS idx_unclaimed_status ON "Unclaimed"(status);
CREATE INDEX IF NOT EXISTS idx_collections_unclaimed_id ON "OverAllCollections"(unclaimed_id);

-- ============================================================================
-- VIEWS
-- ============================================================================

-- Pending View - Items overdue by more than 3 days
DROP VIEW IF EXISTS "Pending";
CREATE VIEW "Pending" 
WITH (security_invoker = true) AS
SELECT 
    id,
    teller_name,
    bet_number,
    draw_date,
    return_date,
    win_amount,
    franchise_name,
    collector,
    area,
    EXTRACT(DAY FROM (NOW() - draw_date::timestamp))::integer AS days_overdue
FROM "Unclaimed"
WHERE status = 'Unclaimed'
AND (NOW() - draw_date::timestamp) > INTERVAL '3 days';

-- PendingCashDeposits View - Collected cash items awaiting deposit
DROP VIEW IF EXISTS "PendingCashDeposits";
CREATE VIEW "PendingCashDeposits" 
WITH (security_invoker = true) AS
SELECT 
    id,
    teller_name,
    bet_number,
    draw_date,
    return_date,
    bet_amount,
    win_amount,
    charge_amount,
    net,
    mode,
    payment_type,
    franchise_name,
    area,
    collector,
    status,
    receipt_image
FROM "Unclaimed"
WHERE status = 'Collected' 
  AND mode = 'Cash' 
  AND (cash_deposited IS NULL OR cash_deposited = FALSE)
ORDER BY return_date DESC;

COMMENT ON VIEW "PendingCashDeposits" IS 'View of collected cash items that have not been deposited to the bank yet';

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- 1. Auto-calculate net amount
CREATE OR REPLACE FUNCTION public.calculate_net_amount()
RETURNS TRIGGER AS $$
BEGIN
    NEW.net = COALESCE(NEW.win_amount, 0) - COALESCE(NEW.charge_amount, 0);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

COMMENT ON FUNCTION calculate_net_amount() IS 'Automatically calculates net amount as win_amount minus charge_amount';

-- 2. Update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 3. Handle unclaimed collection (supports Uncollected and Collected statuses)
CREATE OR REPLACE FUNCTION public.handle_unclaimed_collection()
RETURNS TRIGGER AS $$
BEGIN
    -- Trigger when status changes to either 'Uncollected' (cashier) or 'Collected' (admin/specialist)
    IF (OLD.status IS DISTINCT FROM NEW.status AND (NEW.status = 'Collected' OR NEW.status = 'Uncollected')) THEN
        -- Check if record already exists in OverAllCollections
        IF NOT EXISTS (SELECT 1 FROM public."OverAllCollections" WHERE unclaimed_id = NEW.id) THEN
            -- Insert into OverAllCollections
            INSERT INTO public."OverAllCollections" (
                unclaimed_id, teller_name, bet_number, draw_date, 
                return_date, bet_amount, amount, charge_amount, net, 
                collector, franchise_name, area, receipt_image, mode, payment_type,
                cash_deposited, deposit_date, deposit_amount, deposit_receipt,
                cashier_name, bank_name, deposit_reference
            ) VALUES (
                NEW.id, NEW.teller_name, NEW.bet_number, NEW.draw_date,
                COALESCE(NEW.return_date, NOW()), COALESCE(NEW.bet_amount, 0), NEW.win_amount, 
                COALESCE(NEW.charge_amount, 0), NEW.net,
                COALESCE(NEW.collector, 'System'),
                NEW.franchise_name,
                NEW.area,
                COALESCE(NEW.receipt_image, NEW.deposit_receipt),
                COALESCE(NEW.mode, 'Cash'),
                COALESCE(NEW.payment_type, 'Full Payment'),
                NEW.cash_deposited, NEW.deposit_date, NEW.deposit_amount, NEW.deposit_receipt,
                NEW.cashier_name, NEW.bank_name, NEW.deposit_reference
            );
        END IF;

        -- Check if record already exists in Reports
        IF NOT EXISTS (SELECT 1 FROM public."Reports" WHERE unclaimed_id = NEW.id) THEN
            -- Insert into Reports
            INSERT INTO public."Reports" (
                unclaimed_id, teller_name, bet_number, draw_date, return_date, 
                franchise_name, amount, collector, area,
                staff_amount, collector_amount, agent_amount, admin_amount, total_charges
            ) VALUES (
                NEW.id, NEW.teller_name, NEW.bet_number, NEW.draw_date, 
                COALESCE(NEW.return_date, NOW()), NEW.franchise_name, NEW.win_amount, 
                COALESCE(NEW.collector, 'System'), NEW.area,
                NEW.win_amount * 0.10, -- 10% Staff
                NEW.win_amount * 0.10, -- 10% Collector
                NEW.win_amount * 0.30, -- 30% Agent
                NEW.win_amount * 0.50, -- 50% Admin
                COALESCE(NEW.charge_amount, 0) -- Total charges
            );
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

COMMENT ON FUNCTION handle_unclaimed_collection() IS 'Handles both Uncollected (cashier) and Collected (admin) statuses';

-- 4. Sync updates from Unclaimed to Collections and Reports
CREATE OR REPLACE FUNCTION public.sync_unclaimed_to_collections()
RETURNS TRIGGER AS $$
BEGIN
    -- Only sync if status is Collected or Uncollected (items in collections)
    IF NEW.status IN ('Collected', 'Uncollected') THEN
        -- Update OverAllCollections
        UPDATE public."OverAllCollections"
        SET 
            teller_name = NEW.teller_name,
            bet_number = NEW.bet_number,
            draw_date = NEW.draw_date,
            return_date = COALESCE(NEW.return_date, NOW()),
            bet_amount = COALESCE(NEW.bet_amount, 0),
            amount = NEW.win_amount,
            charge_amount = COALESCE(NEW.charge_amount, 0),
            net = NEW.net,
            collector = COALESCE(NEW.collector, 'System'),
            franchise_name = NEW.franchise_name,
            area = NEW.area,
            receipt_image = NEW.receipt_image,
            mode = COALESCE(NEW.mode, 'Cash'),
            payment_type = COALESCE(NEW.payment_type, 'Full Payment'),
            cash_deposited = NEW.cash_deposited,
            deposit_date = NEW.deposit_date,
            deposit_amount = NEW.deposit_amount,
            deposit_receipt = NEW.deposit_receipt,
            cashier_name = NEW.cashier_name,
            bank_name = NEW.bank_name,
            deposit_reference = NEW.deposit_reference
        WHERE unclaimed_id = NEW.id;
        
        -- Update Reports (also update when charge_amount changes)
        UPDATE public."Reports"
        SET 
            teller_name = NEW.teller_name,
            bet_number = NEW.bet_number,
            draw_date = NEW.draw_date,
            return_date = COALESCE(NEW.return_date, NOW()),
            franchise_name = NEW.franchise_name,
            amount = NEW.win_amount,
            collector = COALESCE(NEW.collector, 'System'),
            area = NEW.area,
            staff_amount = NEW.win_amount * 0.10,
            collector_amount = NEW.win_amount * 0.10,
            agent_amount = NEW.win_amount * 0.30,
            admin_amount = NEW.win_amount * 0.50,
            total_charges = COALESCE(NEW.charge_amount, 0)
        WHERE unclaimed_id = NEW.id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

COMMENT ON FUNCTION sync_unclaimed_to_collections() IS 'Syncs updates from Unclaimed to OverAllCollections and Reports, including charge_amount changes';

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Auto-calculate net amount before insert/update
DROP TRIGGER IF EXISTS calculate_net_before_insert ON "Unclaimed";
CREATE TRIGGER calculate_net_before_insert
    BEFORE INSERT ON "Unclaimed"
    FOR EACH ROW
    EXECUTE FUNCTION calculate_net_amount();

DROP TRIGGER IF EXISTS calculate_net_before_update ON "Unclaimed";
CREATE TRIGGER calculate_net_before_update
    BEFORE UPDATE ON "Unclaimed"
    FOR EACH ROW
    EXECUTE FUNCTION calculate_net_amount();

-- Update updated_at timestamp
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON users 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_unclaimed_updated_at ON "Unclaimed";
CREATE TRIGGER update_unclaimed_updated_at 
    BEFORE UPDATE ON "Unclaimed" 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Handle collection (create records in Collections and Reports)
DROP TRIGGER IF EXISTS on_unclaimed_collected ON "Unclaimed";
CREATE TRIGGER on_unclaimed_collected
    AFTER UPDATE ON "Unclaimed"
    FOR EACH ROW
    WHEN (OLD.status IS DISTINCT FROM NEW.status)
    EXECUTE FUNCTION handle_unclaimed_collection();

-- Sync updates to Collections and Reports
DROP TRIGGER IF EXISTS sync_to_collections_on_update ON "Unclaimed";
CREATE TRIGGER sync_to_collections_on_update
    AFTER UPDATE ON "Unclaimed"
    FOR EACH ROW
    WHEN (NEW.status = 'Collected')
    EXECUTE FUNCTION sync_unclaimed_to_collections();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Unclaimed" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OverAllCollections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reports" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow all to authenticated users" ON users;
DROP POLICY IF EXISTS "Allow all to authenticated users" ON "Unclaimed";
DROP POLICY IF EXISTS "Allow all to authenticated users" ON "OverAllCollections";
DROP POLICY IF EXISTS "Allow all to authenticated users" ON "Reports";
DROP POLICY IF EXISTS "Allow all to anon users" ON users;
DROP POLICY IF EXISTS "Allow all to anon users" ON "Unclaimed";
DROP POLICY IF EXISTS "Allow all to anon users" ON "OverAllCollections";
DROP POLICY IF EXISTS "Allow all to anon users" ON "Reports";

-- Create RLS policies
CREATE POLICY "Allow all to authenticated users" ON users FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated users" ON "Unclaimed" FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated users" ON "OverAllCollections" FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated users" ON "Reports" FOR ALL TO authenticated USING (true);

-- Allow anon for testing (remove in production)
CREATE POLICY "Allow all to anon users" ON users FOR ALL TO anon USING (true);
CREATE POLICY "Allow all to anon users" ON "Unclaimed" FOR ALL TO anon USING (true);
CREATE POLICY "Allow all to anon users" ON "OverAllCollections" FOR ALL TO anon USING (true);
CREATE POLICY "Allow all to anon users" ON "Reports" FOR ALL TO anon USING (true);

-- ============================================================================
-- SEED DATA
-- ============================================================================

-- Default Users
INSERT INTO users (username, password, fullname, role, status) VALUES
('admin', 'admin123', 'Administrator', 'admin', 'active'),
('user', 'user1', 'checker1', 'checker', 'active'),
('GM', 'sgc123', 'GM1', 'general manager', 'active'),
('Rinalou', 'sgc123', 'Unclaimed Specialist', 'specialist', 'active')
ON CONFLICT (username) DO NOTHING;

-- Sample Unclaimed Items
INSERT INTO "Unclaimed" (teller_name, bet_number, draw_date, win_amount, net, franchise_name, status, area) VALUES
('Teller 1', '12-34', CURRENT_DATE - INTERVAL '1 day', 1000.00, 980.00, '5A Royal Gaming OPC', 'Unclaimed', 'Area 1'),
('Teller 2', '56-78', CURRENT_DATE - INTERVAL '5 days', 5000.00, 4900.00, 'Imperial Gnaing OPC', 'Unclaimed', 'Area 2'),
('Teller 1', '90-12', CURRENT_DATE - INTERVAL '10 days', 2500.00, 2450.00, 'Glowing Fortune OPC', 'Unclaimed', 'Area 1'),
('Teller 3', '34-56', CURRENT_DATE - INTERVAL '40 days', 10000.00, 9800.00, '5A Royal Gaming OPC', 'Unclaimed', 'Area 3')
ON CONFLICT DO NOTHING;

-- Sample Collections
INSERT INTO "OverAllCollections" (teller_name, bet_number, draw_date, return_date, amount, charge_amount, net, collector, franchise_name) VALUES
('Teller 4', '11-22', CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '2 days', 2000.00, 40.00, 1960.00, 'Collector A', '5A Royal Gaming OPC')
ON CONFLICT DO NOTHING;

-- Sample Reports
INSERT INTO "Reports" (teller_name, amount, collector, area, staff_amount, collector_amount, agent_amount, admin_amount) VALUES
('Teller 4', 2000.00, 'Collector A', 'Area 1', 200.00, 200.00, 600.00, 1000.00)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SECURITY FIX: Set search_path for all existing functions
-- ============================================================================

-- This automatically fixes all functions in the public schema
DO $$
DECLARE
    func_record RECORD;
BEGIN
    FOR func_record IN 
        SELECT 
            p.oid,
            n.nspname as schema_name,
            p.proname as function_name,
            pg_get_function_identity_arguments(p.oid) as args
        FROM pg_proc p
        JOIN pg_namespace n ON p.pronamespace = n.oid
        WHERE n.nspname = 'public'
    LOOP
        EXECUTE format('ALTER FUNCTION public.%I(%s) SET search_path = public', 
                       func_record.function_name, 
                       func_record.args);
    END LOOP;
END $$;

-- ============================================================================
-- COMPLETION MESSAGE
-- ============================================================================

DO $$
BEGIN
    RAISE NOTICE '✅ STL Unclaimed System Database Schema Created Successfully';
    RAISE NOTICE '✅ All migrations consolidated and applied';
    RAISE NOTICE '✅ Security fixes applied';
    RAISE NOTICE '✅ Ready for production use';
END $$;
