-- Create Areas table for managing service areas
CREATE TABLE IF NOT EXISTS "Areas" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active', -- active, inactive
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_areas_status ON "Areas"(status);
CREATE INDEX IF NOT EXISTS idx_areas_name ON "Areas"(name);

-- Enable RLS
ALTER TABLE "Areas" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
DROP POLICY IF EXISTS "Allow all to authenticated users" ON "Areas";
DROP POLICY IF EXISTS "Allow all to anon users" ON "Areas";

CREATE POLICY "Allow all to authenticated users" ON "Areas" FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to anon users" ON "Areas" FOR ALL TO anon USING (true);

-- Add update trigger
DROP TRIGGER IF EXISTS update_areas_updated_at ON "Areas";
CREATE TRIGGER update_areas_updated_at 
    BEFORE UPDATE ON "Areas" 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Seed with existing areas
INSERT INTO "Areas" (name, description, status) VALUES
('BAROY', 'Baroy Area', 'active'),
('KAPATAGAN', 'Kapatagan Area', 'active'),
('KOLAMBOGAN', 'Kolambogan Area', 'active'),
('LALA', 'Lala Area', 'active'),
('MAIGO', 'Maigo Area', 'active'),
('SALVADOR', 'Salvador Area', 'active'),
('SAPAD', 'Sapad Area', 'active'),
('SND', 'SND Area', 'active'),
('TUBOD', 'Tubod Area', 'active')
ON CONFLICT (name) DO NOTHING;

-- Add comment
COMMENT ON TABLE "Areas" IS 'Manages service areas for the STL Unclaimed System';
